name: "Run Pa11y CI (Node)"
description: "Reusable Node.js action that runs pa11y-ci against a URL or config and uploads a JSON report."
author: "Makepad"
branding:
  icon: check-circle
  color: green

inputs:
  url:
    description: "Single URL to audit (e.g., https://example.com). Ignored if `config` is provided."
    required: false
    default: ""
  config:
    description: "Path to a pa11y-ci config file (JSON/YAML). If set, this takes precedence over `url`."
    required: false
    default: ""
  standard:
    description: "Accessibility standard (WCAG2A, WCAG2AA, WCAG2AAA)."
    required: false
    default: "WCAG2AA"
  threshold:
    description: "Max allowed issues before failing the action. 0 fails on any issue."
    required: false
    default: "0"
  wait:
    description: "Wait time in ms before running (helpful for client-side rendering)."
    required: false
    default: "0"
  headers:
    description: "JSON string of request headers for pa11y-ci (e.g., '{\"Authorization\": \"Bearer ...\"}')."
    required: false
    default: ""
  reporter:
    description: "Reporter for pa11y-ci output (json, csv, html, cli). JSON recommended for CI."
    required: false
    default: "json"
  report_file:
    description: "Output file path for the report (relative to GITHUB_WORKSPACE)."
    required: false
    default: "pa11y-report.json"
  extra_args:
    description: "Extra CLI args passed verbatim to pa11y-ci (advanced)."
    required: false
    default: ""

outputs:
  report_path:
    description: "Path to the generated report file."
  exit_code:
    description: "Exit code from pa11y-ci (0 = success)."

runs:
  using: "node24"
  # Pre & Post hooks for setup/cleanup
  pre: "dist/pre.js"
  main: "dist/index.js"
  post: "dist/post.js"